version: 0.2
env:
  secrets-manager:
    user: "build/or9-poc-docker:user"
    pass: "build/or9-poc-docker:pass"
    dockerhub_user: "build/or9-poc-docker:dockerhub_user"
    dockerhub_pass: "build/or9-poc-docker:dockerhub_pass"
    
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR…
#       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo $dockerhub_pass | docker login -u $dockerhub_user --password-stdin 
      - echo Determining image tag version
      - export IMAGE_TAG_VERSION=${IMAGE_TAG:-$(cat version)}
      - echo Determined IMAGE_TAG_VERSION $IMAGE_TAG_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image…
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION .
#       - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG_VERSION
#       - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION xf0x/codebuild-hello:$IMAGE_TAG_VERSION
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION xf0x/codebuild-hello:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image…
#       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG_VERSION
#       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push xf0x/codebuild-hello:$IMAGE_TAG_VERSION
      - docker push xf0x/codebuild-hello:latest
